CREATE SEQUENCE BOOKING_SEQ
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1;

CREATE TABLE TRAIL (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128) UNIQUE NOT NULL,
    START_AT VARCHAR(128) NOT NULL,
    END_AT VARCHAR(128) NOT NULL,
    UNIT_PRICE DOUBLE NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE BOOKING (
    ID BIGINT NOT NULL DEFAULT NEXT VALUE FOR BOOKING_SEQ,
    TRAIL_ID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (TRAIL_ID) REFERENCES TRAIL(ID)
);

CREATE TABLE HIKER (
    ID BIGINT NOT NULL DEFAULT NEXT VALUE FOR BOOKING_SEQ,
    FIRST_NAME VARCHAR(256) NOT NULL,
    LAST_NAME VARCHAR(256) NOT NULL,
    AGE INTEGER NOT NULL,
    BOOKING_ID BIGINT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING (ID)
);

INSERT INTO TRAIL(NAME, START_AT, END_AT, UNIT_PRICE) VALUES
('Shire', '07:00', '09:00', 29.90),
('Gondor', '10:00', '13:00', 59.90),
('Mordor', '14:00', '19:00', 99.90);